2016-08-29 02:17:23,263 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 02:17:23,272 Starting new HTTPS connection (1): slack.com
2016-08-29 02:17:23,693 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 02:17:23,694 []
2016-08-29 02:17:23,694 []
2016-08-29 02:17:23,795 []
2016-08-29 02:17:23,896 []
2016-08-29 02:17:24,498 []
2016-08-29 02:17:27,107 []
2016-08-29 02:17:31,122 []
2016-08-29 02:17:35,136 []
2016-08-29 02:17:38,548 []
2016-08-29 02:17:39,151 []
2016-08-29 02:17:41,258 []
2016-08-29 02:17:41,258 output from <module 'repeat' from '/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py'>
2016-08-29 02:17:43,165 []
2016-08-29 02:17:45,875 []
2016-08-29 02:17:47,180 []
2016-08-29 02:17:51,193 []
2016-08-29 02:17:55,106 []
2016-08-29 02:17:59,120 []
2016-08-29 02:18:03,134 []
2016-08-29 02:18:07,147 []
2016-08-29 02:18:11,173 []
2016-08-29 02:18:15,187 []
2016-08-29 02:18:19,101 []
2016-08-29 02:18:23,114 []
2016-08-29 02:18:27,128 []
2016-08-29 02:18:31,141 []
2016-08-29 02:18:35,155 []
2016-08-29 02:18:39,168 []
2016-08-29 02:18:43,182 []
2016-08-29 02:18:47,107 []
2016-08-29 02:18:51,121 []
2016-08-29 02:18:55,135 []
2016-08-29 02:18:59,149 []
2016-08-29 02:19:03,164 []
2016-08-29 02:19:07,178 []
2016-08-29 02:19:11,191 []
2016-08-29 02:19:15,105 []
2016-08-29 02:19:19,118 []
2016-08-29 02:19:23,132 []
2016-08-29 02:19:27,146 []
2016-08-29 02:19:31,161 []
2016-08-29 02:19:35,189 []
2016-08-29 02:19:39,103 []
2016-08-29 02:19:43,117 []
2016-08-29 02:19:45,926 []
2016-08-29 02:19:47,131 []
2016-08-29 02:19:51,145 []
2016-08-29 02:19:55,158 []
2016-08-29 02:19:59,172 []
2016-08-29 02:20:03,187 []
2016-08-29 02:20:07,100 []
2016-08-29 02:20:11,114 []
2016-08-29 02:20:15,128 []
2016-08-29 02:20:19,143 []
2016-08-29 02:20:23,157 []
2016-08-29 02:20:27,171 []
2016-08-29 02:20:31,184 []
2016-08-29 02:20:35,199 []
2016-08-29 02:20:39,113 []
2016-08-29 02:20:43,127 []
2016-08-29 02:20:47,141 []
2016-08-29 02:20:51,154 []
2016-08-29 02:20:55,168 []
2016-08-29 02:20:59,182 []
2016-08-29 02:21:03,196 []
2016-08-29 02:21:07,110 []
2016-08-29 02:21:11,124 []
2016-08-29 02:21:15,138 []
2016-08-29 02:21:19,152 []
2016-08-29 02:21:23,165 []
2016-08-29 02:21:27,179 []
2016-08-29 02:21:31,193 []
2016-08-29 02:21:35,106 []
2016-08-29 02:21:39,120 []
2016-08-29 02:21:43,134 []
2016-08-29 02:21:45,843 []
2016-08-29 02:21:47,148 []
2016-08-29 02:21:51,161 []
2016-08-29 02:21:55,175 []
2016-08-29 02:21:59,189 []
2016-08-29 02:22:03,104 []
2016-08-29 02:22:07,119 []
2016-08-29 02:22:11,134 []
2016-08-29 02:22:15,148 []
2016-08-29 02:22:19,162 []
2016-08-29 02:22:23,176 []
2016-08-29 02:22:27,189 []
2016-08-29 02:22:31,102 []
2016-08-29 02:22:35,116 []
2016-08-29 02:22:39,130 []
2016-08-29 02:22:43,144 []
2016-08-29 02:22:47,157 []
2016-08-29 02:22:51,171 []
2016-08-29 02:22:55,185 []
2016-08-29 02:22:59,199 []
2016-08-29 02:23:03,113 []
2016-08-29 02:23:07,127 []
2016-08-29 02:23:11,142 []
2016-08-29 02:23:15,156 []
2016-08-29 02:23:19,170 []
2016-08-29 02:23:23,184 []
2016-08-29 02:23:27,198 []
2016-08-29 02:23:31,112 []
2016-08-29 02:23:35,125 []
2016-08-29 02:23:39,139 []
2016-08-29 02:23:43,152 []
2016-08-29 02:23:45,862 []
2016-08-29 02:23:47,166 []
2016-08-29 02:23:51,180 []
2016-08-29 02:23:55,193 []
2016-08-29 02:23:59,107 []
2016-08-29 02:24:03,120 []
2016-08-29 02:24:07,135 []
2016-08-29 02:24:11,149 []
2016-08-29 02:24:15,164 []
2016-08-29 02:24:19,178 []
2016-08-29 02:24:23,192 []
2016-08-29 02:24:27,105 []
2016-08-29 02:24:31,119 []
2016-08-29 02:24:35,134 []
2016-08-29 02:24:39,148 []
2016-08-29 02:24:43,162 []
2016-08-29 02:24:47,176 []
2016-08-29 02:24:51,191 []
2016-08-29 02:24:55,104 []
2016-08-29 02:24:59,118 []
2016-08-29 02:25:03,131 []
2016-08-29 02:25:07,145 []
2016-08-29 02:25:11,159 []
2016-08-29 02:25:15,172 []
2016-08-29 02:25:19,186 []
2016-08-29 02:25:23,199 []
2016-08-29 02:25:27,112 []
2016-08-29 02:25:31,126 []
2016-08-29 02:25:35,140 []
2016-08-29 02:25:39,153 []
2016-08-29 02:25:43,167 []
2016-08-29 02:25:47,181 []
2016-08-29 02:25:51,194 []
2016-08-29 02:25:55,107 []
2016-08-29 02:25:59,121 []
2016-08-29 02:26:03,134 []
2016-08-29 02:26:07,148 []
2016-08-29 02:26:11,162 []
2016-08-29 02:26:15,176 []
2016-08-29 02:26:19,189 []
2016-08-29 02:26:23,102 []
2016-08-29 02:26:27,116 []
2016-08-29 02:26:31,129 []
2016-08-29 02:26:35,142 []
2016-08-29 02:26:39,156 []
2016-08-29 02:26:43,170 []
2016-08-29 02:26:45,879 []
2016-08-29 02:26:47,183 []
2016-08-29 02:26:51,197 []
2016-08-29 02:26:55,110 []
2016-08-29 02:26:59,123 []
2016-08-29 02:27:03,137 []
2016-08-29 02:27:07,150 []
2016-08-29 02:27:11,164 []
2016-08-29 02:27:15,177 []
2016-08-29 02:27:19,191 []
2016-08-29 02:27:23,104 []
2016-08-29 02:27:27,117 []
2016-08-29 02:27:31,131 []
2016-08-29 03:56:14,417 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 03:56:14,422 Starting new HTTPS connection (1): slack.com
2016-08-29 03:56:14,840 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 03:56:14,840 []
2016-08-29 03:56:14,841 []
2016-08-29 03:56:14,941 []
2016-08-29 03:56:15,042 []
2016-08-29 03:56:15,645 []
2016-08-29 03:56:16,949 []
2016-08-29 03:56:18,153 []
2016-08-29 03:56:18,856 []
2016-08-29 03:56:18,856 output from <module 'repeat' from '/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py'>
2016-08-29 03:56:22,167 []
2016-08-29 04:24:08,885 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 04:24:08,891 Starting new HTTPS connection (1): slack.com
2016-08-29 04:24:09,293 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 04:26:49,321 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 04:26:49,327 Starting new HTTPS connection (1): slack.com
2016-08-29 04:26:49,726 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 04:26:50,415 []
2016-08-29 04:26:50,415 []
2016-08-29 04:26:50,516 []
2016-08-29 04:26:50,617 []
2016-08-29 04:26:50,717 []
2016-08-29 04:26:54,129 []
2016-08-29 04:26:58,143 []
2016-08-29 04:27:02,157 []
2016-08-29 04:27:02,860 []
2016-08-29 04:27:04,366 []
2016-08-29 04:27:06,072 []
2016-08-29 04:27:06,074 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472444825.000007', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 45, in process_message
    model = create_model(sess, True)
NameError: global name 'create_model' is not defined
2016-08-29 04:27:06,175 []
2016-08-29 04:27:10,189 []
2016-08-29 04:27:14,103 []
2016-08-29 04:27:18,118 []
2016-08-29 04:27:22,132 []
2016-08-29 04:27:26,146 []
2016-08-29 04:27:30,159 []
2016-08-29 04:27:34,173 []
2016-08-29 04:27:38,187 []
2016-08-29 04:27:42,200 []
2016-08-29 04:27:46,114 []
2016-08-29 04:27:50,128 []
2016-08-29 04:27:54,142 []
2016-08-29 04:27:58,156 []
2016-08-29 04:28:02,171 []
2016-08-29 04:28:06,185 []
2016-08-29 04:28:10,198 []
2016-08-29 04:28:14,111 []
2016-08-29 04:28:18,124 []
2016-08-29 04:28:22,138 []
2016-08-29 04:28:26,152 []
2016-08-29 04:28:30,166 []
2016-08-29 04:28:34,180 []
2016-08-29 04:28:38,194 []
2016-08-29 04:28:42,107 []
2016-08-29 04:28:46,120 []
2016-08-29 04:28:50,133 []
2016-08-29 04:28:54,147 []
2016-08-29 04:28:58,161 []
2016-08-29 04:29:02,174 []
2016-08-29 04:29:06,188 []
2016-08-29 04:29:10,102 []
2016-08-29 04:29:14,116 []
2016-08-29 04:29:18,130 []
2016-08-29 04:29:22,144 []
2016-08-29 04:29:26,159 []
2016-08-29 04:29:30,173 []
2016-08-29 04:29:34,188 []
2016-08-29 04:29:38,102 []
2016-08-29 04:29:42,117 []
2016-08-29 04:29:45,930 []
2016-08-29 04:29:46,132 []
2016-08-29 04:29:50,146 []
2016-08-29 04:29:54,160 []
2016-08-29 04:29:58,174 []
2016-08-29 04:30:02,188 []
2016-08-29 04:30:06,102 []
2016-08-29 04:30:10,116 []
2016-08-29 04:30:14,130 []
2016-08-29 04:30:18,144 []
2016-08-29 04:30:22,158 []
2016-08-29 04:30:26,172 []
2016-08-29 04:30:30,185 []
2016-08-29 04:30:34,199 []
2016-08-29 04:30:38,115 []
2016-08-29 04:30:42,130 []
2016-08-29 04:30:46,144 []
2016-08-29 04:30:50,159 []
2016-08-29 04:30:54,172 []
2016-08-29 04:30:58,197 []
2016-08-29 04:31:02,111 []
2016-08-29 04:31:06,128 []
2016-08-29 04:31:10,144 []
2016-08-29 04:31:14,159 []
2016-08-29 04:31:18,173 []
2016-08-29 04:31:22,187 []
2016-08-29 04:31:26,101 []
2016-08-29 04:31:30,116 []
2016-08-29 04:31:34,156 []
2016-08-29 04:31:38,170 []
2016-08-29 04:31:42,188 []
2016-08-29 04:31:46,102 []
2016-08-29 04:31:50,116 []
2016-08-29 04:31:54,130 []
2016-08-29 04:31:58,153 []
2016-08-29 04:32:02,167 []
2016-08-29 04:32:06,181 []
2016-08-29 04:32:10,195 []
2016-08-29 04:32:14,108 []
2016-08-29 04:32:18,122 []
2016-08-29 04:32:22,136 []
2016-08-29 04:32:26,151 []
2016-08-29 04:32:30,165 []
2016-08-29 04:32:34,178 []
2016-08-29 04:32:38,192 []
2016-08-29 04:32:42,106 []
2016-08-29 04:32:45,919 []
2016-08-29 04:32:46,120 []
2016-08-29 04:32:50,134 []
2016-08-29 04:32:54,149 []
2016-08-29 04:32:58,171 []
2016-08-29 04:33:02,185 []
2016-08-29 04:33:06,200 []
2016-08-29 04:33:10,113 []
2016-08-29 04:33:14,133 []
2016-08-29 04:33:18,147 []
2016-08-29 04:33:22,161 []
2016-08-29 04:33:26,175 []
2016-08-29 04:33:30,189 []
2016-08-29 04:33:34,103 []
2016-08-29 04:33:38,116 []
2016-08-29 04:33:42,130 []
2016-08-29 04:33:46,145 []
2016-08-29 04:33:50,159 []
2016-08-29 04:33:54,173 []
2016-08-29 04:33:58,187 []
2016-08-29 04:34:02,101 []
2016-08-29 04:34:06,114 []
2016-08-29 04:34:10,127 []
2016-08-29 04:34:14,141 []
2016-08-29 04:34:18,154 []
2016-08-29 04:34:22,168 []
2016-08-29 04:34:26,182 []
2016-08-29 04:34:30,197 []
2016-08-29 04:34:34,112 []
2016-08-29 04:34:38,127 []
2016-08-29 04:34:42,141 []
2016-08-29 04:34:45,855 []
2016-08-29 04:34:46,156 []
2016-08-29 04:34:50,171 []
2016-08-29 04:34:54,185 []
2016-08-29 04:34:58,199 []
2016-08-29 04:35:02,113 []
2016-08-29 04:35:06,127 []
2016-08-29 04:35:10,141 []
2016-08-29 04:35:14,155 []
2016-08-29 04:35:18,170 []
2016-08-29 04:35:22,184 []
2016-08-29 04:35:26,199 []
2016-08-29 04:35:30,113 []
2016-08-29 04:35:34,127 []
2016-08-29 04:35:38,141 []
2016-08-29 04:35:42,156 []
2016-08-29 04:35:46,170 []
2016-08-29 04:35:50,184 []
2016-08-29 04:35:54,198 []
2016-08-29 04:35:58,111 []
2016-08-29 04:36:02,124 []
2016-08-29 04:36:06,137 []
2016-08-29 04:36:10,151 []
2016-08-29 04:36:14,165 []
2016-08-29 04:36:18,178 []
2016-08-29 04:36:22,193 []
2016-08-29 04:36:26,107 []
2016-08-29 04:36:30,122 []
2016-08-29 04:36:34,136 []
2016-08-29 04:36:38,150 []
2016-08-29 04:36:42,164 []
2016-08-29 04:36:46,178 []
2016-08-29 04:36:50,192 []
2016-08-29 04:36:54,105 []
2016-08-29 04:36:58,119 []
2016-08-29 04:37:02,132 []
2016-08-29 04:37:06,146 []
2016-08-29 04:37:10,160 []
2016-08-29 04:37:14,173 []
2016-08-29 04:37:18,187 []
2016-08-29 04:37:22,101 []
2016-08-29 04:37:26,115 []
2016-08-29 04:37:30,129 []
2016-08-29 04:37:34,143 []
2016-08-29 04:37:38,158 []
2016-08-29 04:37:42,172 []
2016-08-29 04:37:45,885 []
2016-08-29 04:37:46,187 []
2016-08-29 04:37:50,101 []
2016-08-29 04:37:54,115 []
2016-08-29 04:37:58,129 []
2016-08-29 04:38:02,144 []
2016-08-29 04:41:23,144 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 04:41:23,149 Starting new HTTPS connection (1): slack.com
2016-08-29 04:41:23,558 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 04:41:24,223 []
2016-08-29 04:41:24,223 []
2016-08-29 04:41:24,324 []
2016-08-29 04:41:24,425 []
2016-08-29 04:41:24,526 []
2016-08-29 04:41:28,139 []
2016-08-29 04:41:30,448 []
2016-08-29 04:41:32,155 []
2016-08-29 04:41:32,256 []
2016-08-29 04:41:34,063 []
2016-08-29 04:41:34,066 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472445693.000008', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 47, in process_message
    model = create_model(sess, True)
NameError: global name 'create_model' is not defined
2016-08-29 04:41:36,175 []
2016-08-29 04:41:40,190 []
2016-08-29 04:41:44,104 []
2016-08-29 04:41:45,911 []
2016-08-29 04:41:48,120 []
2016-08-29 04:41:52,136 []
2016-08-29 04:41:56,152 []
2016-08-29 04:42:00,168 []
2016-08-29 04:42:04,185 []
2016-08-29 04:42:08,201 []
2016-08-29 04:42:12,116 []
2016-08-29 04:42:16,132 []
2016-08-29 04:48:31,513 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 04:48:31,519 Starting new HTTPS connection (1): slack.com
2016-08-29 04:48:31,900 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 04:48:32,576 []
2016-08-29 04:48:32,576 []
2016-08-29 04:48:32,677 []
2016-08-29 04:48:32,778 []
2016-08-29 04:48:32,979 []
2016-08-29 04:48:36,191 []
2016-08-29 04:48:38,700 []
2016-08-29 04:48:40,105 []
2016-08-29 04:48:41,410 []
2016-08-29 04:48:41,412 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472446121.000009', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 50, in process_message
    tf.app.run()
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 29, in run
    main = main or sys.modules['__main__'].main
AttributeError: 'module' object has no attribute 'main'
2016-08-29 04:48:44,121 []
2016-08-29 04:48:45,928 []
2016-08-29 04:48:48,136 []
2016-08-29 04:48:52,150 []
2016-08-29 04:48:56,165 []
2016-08-29 04:49:00,179 []
2016-08-29 04:49:04,194 []
2016-08-29 04:49:08,108 []
2016-08-29 04:49:12,122 []
2016-08-29 04:49:16,136 []
2016-08-29 04:49:20,149 []
2016-08-29 04:49:24,163 []
2016-08-29 04:49:28,176 []
2016-08-29 04:55:34,633 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 04:55:34,641 Starting new HTTPS connection (1): slack.com
2016-08-29 04:55:34,950 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 04:55:35,901 []
2016-08-29 04:55:35,901 []
2016-08-29 04:55:36,002 []
2016-08-29 04:55:36,103 []
2016-08-29 04:55:36,204 []
2016-08-29 04:55:39,114 []
2016-08-29 04:55:42,740 []
2016-08-29 04:55:43,142 []
2016-08-29 04:55:43,544 []
2016-08-29 04:55:44,147 []
2016-08-29 04:55:44,149 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472446543.000010', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 50, in process_message
    tf.app.run()
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 29, in run
    main = main or sys.modules['__main__'].main
AttributeError: 'module' object has no attribute 'main'
2016-08-29 04:55:45,956 []
2016-08-29 04:55:47,161 []
2016-08-29 04:55:51,175 []
2016-08-29 04:55:55,189 []
2016-08-29 04:55:59,103 []
2016-08-29 04:56:03,117 []
2016-08-29 04:56:07,132 []
2016-08-29 04:56:11,148 []
2016-08-29 04:56:15,163 []
2016-08-29 04:56:19,178 []
2016-08-29 04:56:23,192 []
2016-08-29 04:56:27,106 []
2016-08-29 04:56:31,121 []
2016-08-29 04:56:35,136 []
2016-08-29 04:56:39,150 []
2016-08-29 04:56:43,164 []
2016-08-29 04:56:47,178 []
2016-08-29 04:56:51,192 []
2016-08-29 04:56:55,106 []
2016-08-29 04:56:59,119 []
2016-08-29 04:57:03,133 []
2016-08-29 04:57:07,148 []
2016-08-29 04:57:11,163 []
2016-08-29 04:57:15,178 []
2016-08-29 04:57:19,193 []
2016-08-29 04:57:23,107 []
2016-08-29 04:57:27,121 []
2016-08-29 04:57:31,135 []
2016-08-29 04:57:35,148 []
2016-08-29 04:57:39,162 []
2016-08-29 04:57:43,176 []
2016-08-29 04:57:45,885 []
2016-08-29 04:57:47,190 []
2016-08-29 04:57:51,104 []
2016-08-29 04:57:55,118 []
2016-08-29 04:57:59,133 []
2016-08-29 04:58:03,148 []
2016-08-29 04:58:07,162 []
2016-08-29 04:58:11,177 []
2016-08-29 04:58:15,192 []
2016-08-29 04:58:19,106 []
2016-08-29 04:58:23,121 []
2016-08-29 04:58:27,136 []
2016-08-29 04:58:31,150 []
2016-08-29 04:58:35,165 []
2016-08-29 04:58:39,179 []
2016-08-29 04:58:43,193 []
2016-08-29 04:58:47,106 []
2016-08-29 04:58:51,121 []
2016-08-29 04:58:55,135 []
2016-08-29 04:58:59,150 []
2016-08-29 04:59:03,165 []
2016-08-29 04:59:07,179 []
2016-08-29 04:59:11,194 []
2016-08-29 04:59:15,108 []
2016-08-29 04:59:19,122 []
2016-08-29 04:59:23,137 []
2016-08-29 04:59:27,151 []
2016-08-29 04:59:31,165 []
2016-08-29 04:59:35,179 []
2016-08-29 04:59:39,193 []
2016-08-29 04:59:43,107 []
2016-08-29 04:59:47,121 []
2016-08-29 04:59:51,135 []
2016-08-29 04:59:55,149 []
2016-08-29 04:59:59,164 []
2016-08-29 05:00:03,178 []
2016-08-29 05:00:07,193 []
2016-08-29 05:00:11,107 []
2016-08-29 05:00:15,121 []
2016-08-29 05:00:19,136 []
2016-08-29 05:00:23,150 []
2016-08-29 05:00:27,165 []
2016-08-29 05:00:31,179 []
2016-08-29 05:00:35,194 []
2016-08-29 05:00:39,107 []
2016-08-29 05:00:43,121 []
2016-08-29 05:00:45,932 []
2016-08-29 05:00:47,136 []
2016-08-29 05:00:51,151 []
2016-08-29 05:00:55,165 []
2016-08-29 05:00:59,180 []
2016-08-29 05:01:03,194 []
2016-08-29 05:01:07,109 []
2016-08-29 05:01:11,124 []
2016-08-29 05:01:15,138 []
2016-08-29 05:01:19,153 []
2016-08-29 05:01:23,167 []
2016-08-29 05:01:27,181 []
2016-08-29 05:01:31,195 []
2016-08-29 05:01:35,109 []
2016-08-29 05:01:39,123 []
2016-08-29 05:01:43,137 []
2016-08-29 05:01:47,151 []
2016-08-29 05:01:51,165 []
2016-08-29 05:01:55,178 []
2016-08-29 05:01:59,192 []
2016-08-29 05:02:03,106 []
2016-08-29 05:02:07,120 []
2016-08-29 05:02:11,134 []
2016-08-29 05:02:15,147 []
2016-08-29 05:02:19,161 []
2016-08-29 05:02:23,175 []
2016-08-29 05:02:27,189 []
2016-08-29 05:02:31,102 []
2016-08-29 05:02:35,116 []
2016-08-29 05:02:39,130 []
2016-08-29 05:02:43,144 []
2016-08-29 05:02:47,158 []
2016-08-29 05:02:51,172 []
2016-08-29 05:02:55,186 []
2016-08-29 05:02:59,200 []
2016-08-29 05:03:01,810 []
2016-08-29 05:03:02,211 []
2016-08-29 05:03:02,212 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472446982.000011', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 50, in process_message
    tf.app.run()
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 29, in run
    main = main or sys.modules['__main__'].main
AttributeError: 'module' object has no attribute 'main'
2016-08-29 05:03:03,116 []
2016-08-29 05:04:54,177 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:04:54,183 Starting new HTTPS connection (1): slack.com
2016-08-29 05:04:54,556 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:04:55,256 []
2016-08-29 05:04:55,256 []
2016-08-29 05:04:55,357 []
2016-08-29 05:04:55,458 []
2016-08-29 05:04:55,558 []
2016-08-29 05:04:58,670 []
2016-08-29 05:04:59,172 []
2016-08-29 05:04:59,273 []
2016-08-29 05:04:59,274 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472447099.000012', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 46, in process_message
    tf.app.run()
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 29, in run
    main = main or sys.modules['__main__'].main
AttributeError: 'module' object has no attribute 'main'
2016-08-29 05:05:03,189 []
2016-08-29 05:05:07,103 []
2016-08-29 05:05:11,119 []
2016-08-29 05:05:15,146 []
2016-08-29 05:05:19,162 []
2016-08-29 05:05:23,177 []
2016-08-29 05:05:27,192 []
2016-08-29 05:05:31,106 []
2016-08-29 05:05:35,121 []
2016-08-29 05:05:39,135 []
2016-08-29 05:05:43,153 []
2016-08-29 05:05:45,863 []
2016-08-29 05:05:47,168 []
2016-08-29 05:05:51,182 []
2016-08-29 05:05:55,199 []
2016-08-29 05:05:59,114 []
2016-08-29 05:06:03,128 []
2016-08-29 05:06:07,143 []
2016-08-29 05:06:11,157 []
2016-08-29 05:06:15,171 []
2016-08-29 05:06:19,185 []
2016-08-29 05:06:23,199 []
2016-08-29 05:06:27,113 []
2016-08-29 05:06:31,127 []
2016-08-29 05:06:35,152 []
2016-08-29 05:06:39,168 []
2016-08-29 05:06:43,183 []
2016-08-29 05:06:47,198 []
2016-08-29 05:06:51,112 []
2016-08-29 05:18:54,961 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:18:54,966 Starting new HTTPS connection (1): slack.com
2016-08-29 05:18:55,500 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:18:56,163 []
2016-08-29 05:18:56,163 []
2016-08-29 05:18:56,264 []
2016-08-29 05:18:56,364 []
2016-08-29 05:18:56,465 []
2016-08-29 05:19:00,178 []
2016-08-29 05:19:04,193 []
2016-08-29 05:19:05,698 []
2016-08-29 05:19:06,903 []
2016-08-29 05:19:08,107 []
2016-08-29 05:19:09,512 []
2016-08-29 05:19:10,817 []
2016-08-29 05:19:11,620 []
2016-08-29 05:19:11,620 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472447951.000013', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 46, in process_message
    tf.app.run()
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 29, in run
    main = main or sys.modules['__main__'].main
AttributeError: 'module' object has no attribute 'main'
2016-08-29 05:19:12,122 []
2016-08-29 05:19:16,136 []
2016-08-29 05:21:47,601 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:21:47,608 Starting new HTTPS connection (1): slack.com
2016-08-29 05:21:47,927 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:21:48,597 []
2016-08-29 05:21:48,598 []
2016-08-29 05:21:48,698 []
2016-08-29 05:21:48,799 []
2016-08-29 05:21:48,900 []
2016-08-29 05:21:49,000 []
2016-08-29 05:21:49,904 []
2016-08-29 05:21:50,406 []
2016-08-29 05:21:50,407 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472448110.000014', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 47, in process_message
    text = trans.decode_main(data['text'])
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/x_translate.py", line 309, in decode_main
    tf.app.run()
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 29, in run
    main = main or sys.modules['__main__'].main
AttributeError: 'module' object has no attribute 'main'
2016-08-29 05:21:52,113 []
2016-08-29 05:21:56,128 []
2016-08-29 05:22:00,143 []
2016-08-29 05:22:04,157 []
2016-08-29 05:22:08,172 []
2016-08-29 05:22:12,186 []
2016-08-29 05:22:16,101 []
2016-08-29 05:22:20,115 []
2016-08-29 05:22:24,129 []
2016-08-29 05:22:28,144 []
2016-08-29 05:22:32,158 []
2016-08-29 05:22:36,173 []
2016-08-29 05:22:40,188 []
2016-08-29 05:22:44,102 []
2016-08-29 05:22:48,117 []
2016-08-29 05:22:52,134 []
2016-08-29 05:22:56,149 []
2016-08-29 05:23:00,165 []
2016-08-29 05:23:04,181 []
2016-08-29 05:23:08,197 []
2016-08-29 05:23:12,112 []
2016-08-29 05:23:16,129 []
2016-08-29 05:23:20,144 []
2016-08-29 05:23:24,160 []
2016-08-29 05:23:28,176 []
2016-08-29 05:23:32,191 []
2016-08-29 05:23:36,106 []
2016-08-29 05:23:40,121 []
2016-08-29 05:23:44,136 []
2016-08-29 05:23:48,151 []
2016-08-29 05:23:52,166 []
2016-08-29 05:23:56,181 []
2016-08-29 05:24:00,197 []
2016-08-29 05:24:04,111 []
2016-08-29 05:24:08,126 []
2016-08-29 05:24:12,142 []
2016-08-29 05:24:16,157 []
2016-08-29 05:24:20,172 []
2016-08-29 05:24:24,187 []
2016-08-29 05:24:28,102 []
2016-08-29 05:24:32,118 []
2016-08-29 05:24:36,134 []
2016-08-29 05:24:40,150 []
2016-08-29 05:24:44,165 []
2016-08-29 05:24:45,872 []
2016-08-29 05:24:48,181 []
2016-08-29 05:24:52,196 []
2016-08-29 05:24:56,110 []
2016-08-29 05:25:00,125 []
2016-08-29 05:25:04,140 []
2016-08-29 05:25:08,155 []
2016-08-29 05:25:12,170 []
2016-08-29 05:25:16,185 []
2016-08-29 05:25:20,100 []
2016-08-29 05:25:24,115 []
2016-08-29 05:25:28,130 []
2016-08-29 05:25:32,145 []
2016-08-29 05:25:36,160 []
2016-08-29 05:25:40,175 []
2016-08-29 05:25:44,190 []
2016-08-29 05:25:48,104 []
2016-08-29 05:25:52,119 []
2016-08-29 05:25:56,134 []
2016-08-29 05:26:00,149 []
2016-08-29 05:26:04,164 []
2016-08-29 05:26:08,179 []
2016-08-29 05:26:12,194 []
2016-08-29 05:26:16,109 []
2016-08-29 05:26:20,125 []
2016-08-29 05:26:24,141 []
2016-08-29 05:26:28,157 []
2016-08-29 05:26:32,173 []
2016-08-29 05:26:36,188 []
2016-08-29 05:26:40,103 []
2016-08-29 05:26:44,117 []
2016-08-29 05:26:48,132 []
2016-08-29 05:26:52,147 []
2016-08-29 05:26:56,161 []
2016-08-29 05:27:00,175 []
2016-08-29 05:27:04,189 []
2016-08-29 05:27:08,104 []
2016-08-29 05:27:12,119 []
2016-08-29 05:27:16,133 []
2016-08-29 05:27:20,148 []
2016-08-29 05:27:24,162 []
2016-08-29 05:27:28,176 []
2016-08-29 05:27:32,190 []
2016-08-29 05:27:36,103 []
2016-08-29 05:27:40,118 []
2016-08-29 05:27:44,134 []
2016-08-29 05:27:45,941 []
2016-08-29 05:27:48,149 []
2016-08-29 05:27:52,163 []
2016-08-29 05:27:56,178 []
2016-08-29 05:28:00,196 []
2016-08-29 05:28:04,110 []
2016-08-29 05:28:08,125 []
2016-08-29 05:28:12,154 []
2016-08-29 05:28:16,168 []
2016-08-29 05:28:20,182 []
2016-08-29 05:28:24,197 []
2016-08-29 05:30:30,447 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:30:30,452 Starting new HTTPS connection (1): slack.com
2016-08-29 05:30:30,745 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:30:35,963 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:30:35,969 Starting new HTTPS connection (1): slack.com
2016-08-29 05:30:36,253 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:30:57,911 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:30:57,916 Starting new HTTPS connection (1): slack.com
2016-08-29 05:30:58,283 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:30:58,974 []
2016-08-29 05:30:58,975 []
2016-08-29 05:30:59,076 []
2016-08-29 05:30:59,176 []
2016-08-29 05:30:59,277 []
2016-08-29 05:31:02,188 []
2016-08-29 05:31:03,092 []
2016-08-29 05:31:03,895 []
2016-08-29 05:31:03,896 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472448663.000015', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 48, in process_message
    text = trans.decode_main(data['text'])
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/x_translate.py", line 309, in decode_main
    tf.app.run()
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 29, in run
    main = main or sys.modules['__main__'].main
AttributeError: 'module' object has no attribute 'main'
2016-08-29 05:31:06,104 []
2016-08-29 05:31:10,118 []
2016-08-29 05:31:14,134 []
2016-08-29 05:31:18,148 []
2016-08-29 05:31:22,162 []
2016-08-29 05:31:26,177 []
2016-08-29 05:31:30,191 []
2016-08-29 05:31:34,106 []
2016-08-29 05:31:38,120 []
2016-08-29 05:34:25,128 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:34:25,133 Starting new HTTPS connection (1): slack.com
2016-08-29 05:34:25,491 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:34:26,158 []
2016-08-29 05:34:26,158 []
2016-08-29 05:34:26,259 []
2016-08-29 05:34:26,360 []
2016-08-29 05:34:26,461 []
2016-08-29 05:34:26,562 []
2016-08-29 05:34:29,171 []
2016-08-29 05:34:30,175 []
2016-08-29 05:34:30,175 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472448869.000016', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 48, in process_message
    text = trans.decode_main(data['text'])
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/x_translate.py", line 309, in decode_main
    tf.app.run()
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 29, in run
    main = main or sys.modules['__main__'].main
AttributeError: 'module' object has no attribute 'main'
2016-08-29 05:34:30,276 []
2016-08-29 05:34:34,190 []
2016-08-29 05:34:38,103 []
2016-08-29 05:34:42,117 []
2016-08-29 05:34:46,132 []
2016-08-29 05:34:50,145 []
2016-08-29 05:34:54,159 []
2016-08-29 05:34:58,173 []
2016-08-29 05:35:02,187 []
2016-08-29 05:35:06,101 []
2016-08-29 05:35:10,114 []
2016-08-29 05:35:14,128 []
2016-08-29 05:44:06,087 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:44:06,092 Starting new HTTPS connection (1): slack.com
2016-08-29 05:44:06,484 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:44:07,192 []
2016-08-29 05:44:07,193 []
2016-08-29 05:44:07,294 []
2016-08-29 05:44:07,394 []
2016-08-29 05:44:07,495 []
2016-08-29 05:44:09,903 []
2016-08-29 05:44:10,606 []
2016-08-29 05:44:10,607 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472449450.000017', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 48, in process_message
    text = trans.decode_main(data['text'])
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/x_translate.py", line 309, in decode_main
    tf.app.run()
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
TypeError: main() takes no arguments (1 given)
2016-08-29 05:44:11,109 []
2016-08-29 05:44:15,122 []
2016-08-29 05:44:28,950 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:44:28,956 Starting new HTTPS connection (1): slack.com
2016-08-29 05:44:29,321 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:44:29,981 []
2016-08-29 05:44:29,982 []
2016-08-29 05:44:30,082 []
2016-08-29 05:44:30,183 []
2016-08-29 05:44:30,284 []
2016-08-29 05:44:30,384 []
2016-08-29 05:44:30,786 []
2016-08-29 05:44:31,289 []
2016-08-29 05:45:22,146 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:45:22,152 Starting new HTTPS connection (1): slack.com
2016-08-29 05:45:22,511 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:47:19,599 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 05:47:19,606 Starting new HTTPS connection (1): slack.com
2016-08-29 05:47:19,922 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 05:47:19,924 []
2016-08-29 05:47:19,924 []
2016-08-29 05:47:20,025 []
2016-08-29 05:47:20,126 []
2016-08-29 05:47:20,628 []
2016-08-29 05:47:20,929 []
2016-08-29 05:47:21,130 []
2016-08-29 05:52:24,821 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472449640.000019', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 48, in process_message
    text = trans.decode_main(data['text'])
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/x_translate.py", line 329, in decode_main
    text = mf.mecab(sentence)
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/MeCabFuji.py", line 73, in mecab
    result_node = m.parseToNode(text)
  File "/usr/lib/python2.7/dist-packages/MeCab.py", line 282, in parseToNode
    def parseToNode(self, *args): return _MeCab.Tagger_parseToNode(self, *args)
TypeError: in method 'Tagger_parseToNode', argument 2 of type 'char const *'
2016-08-29 05:52:26,403 Starting new HTTPS connection (1): slack.com
2016-08-29 05:52:26,893 []
2016-08-29 05:52:26,994 []
2016-08-29 05:52:27,496 []
2016-08-29 05:52:27,597 []
2016-08-29 05:52:30,106 []
2016-08-29 05:52:34,121 []
2016-08-29 05:52:38,135 []
2016-08-29 05:52:42,150 []
2016-08-29 05:52:46,164 []
2016-08-29 05:52:50,179 []
2016-08-29 05:52:54,193 []
2016-08-29 05:52:58,107 []
2016-08-29 05:53:02,122 []
2016-08-29 05:53:06,136 []
2016-08-29 05:53:10,149 []
2016-08-29 05:53:14,163 []
2016-08-29 05:53:18,177 []
2016-08-29 05:53:22,190 []
2016-08-29 05:53:26,105 []
2016-08-29 05:53:30,119 []
2016-08-29 05:53:34,133 []
2016-08-29 05:53:38,148 []
2016-08-29 05:53:42,162 []
2016-08-29 05:53:46,177 []
2016-08-29 05:53:50,191 []
2016-08-29 05:53:54,104 []
2016-08-29 05:53:58,120 []
2016-08-29 05:54:02,136 []
2016-08-29 05:54:06,153 []
2016-08-29 05:54:10,169 []
2016-08-29 05:54:14,186 []
2016-08-29 05:54:18,102 []
2016-08-29 05:54:22,118 []
2016-08-29 05:54:26,134 []
2016-08-29 05:54:30,151 []
2016-08-29 05:54:34,168 []
2016-08-29 05:54:38,184 []
2016-08-29 05:54:42,100 []
2016-08-29 05:54:45,916 []
2016-08-29 05:54:46,117 []
2016-08-29 05:54:50,133 []
2016-08-29 05:54:54,150 []
2016-08-29 05:54:58,165 []
2016-08-29 05:55:02,181 []
2016-08-29 05:55:06,196 []
2016-08-29 05:55:10,111 []
2016-08-29 05:55:14,125 []
2016-08-29 05:55:18,140 []
2016-08-29 05:55:22,154 []
2016-08-29 05:55:26,168 []
2016-08-29 05:55:30,182 []
2016-08-29 05:55:34,197 []
2016-08-29 05:55:38,111 []
2016-08-29 05:55:42,126 []
2016-08-29 05:55:46,140 []
2016-08-29 05:55:50,155 []
2016-08-29 05:55:54,171 []
2016-08-29 05:55:58,185 []
2016-08-29 05:56:02,200 []
2016-08-29 05:56:06,114 []
2016-08-29 05:56:10,129 []
2016-08-29 05:56:14,144 []
2016-08-29 05:56:18,158 []
2016-08-29 05:56:22,172 []
2016-08-29 05:56:26,186 []
2016-08-29 05:56:30,199 []
2016-08-29 05:56:34,113 []
2016-08-29 05:56:38,127 []
2016-08-29 05:56:42,141 []
2016-08-29 05:56:45,954 []
2016-08-29 05:56:46,155 []
2016-08-29 06:00:09,978 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 06:00:09,986 Starting new HTTPS connection (1): slack.com
2016-08-29 06:00:10,395 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 06:00:10,397 []
2016-08-29 06:00:10,397 []
2016-08-29 06:00:10,498 []
2016-08-29 06:00:10,599 []
2016-08-29 06:00:11,302 []
2016-08-29 06:00:14,112 []
2016-08-29 06:00:18,126 []
2016-08-29 06:00:22,141 []
2016-08-29 06:00:26,156 []
2016-08-29 06:00:30,171 []
2016-08-29 06:00:33,784 []
2016-08-29 06:00:34,186 []
2016-08-29 06:00:34,388 []
2016-08-29 06:02:48,280 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 06:02:48,290 Starting new HTTPS connection (1): slack.com
2016-08-29 06:02:48,592 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 06:02:48,595 []
2016-08-29 06:02:48,595 []
2016-08-29 06:02:48,696 []
2016-08-29 06:02:48,797 []
2016-08-29 06:02:49,500 []
2016-08-29 06:02:52,009 []
2016-08-29 06:02:52,109 []
2016-08-29 06:02:52,612 []
2016-08-29 06:07:08,500 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472450572.000021', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 48, in process_message
    text = trans.decode_main(data['text'])
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/x_translate.py", line 353, in decode_main
    print(" ".join([rev_out_vocab[output] for output in outputs]))
IndexError: list index out of range
2016-08-29 06:07:10,411 Starting new HTTPS connection (1): slack.com
2016-08-29 06:07:10,874 []
2016-08-29 06:07:10,975 []
2016-08-29 06:07:11,076 []
2016-08-29 06:07:11,176 []
2016-08-29 06:07:14,187 []
2016-08-29 06:07:18,101 []
2016-08-29 06:07:22,115 []
2016-08-29 06:07:26,131 []
2016-08-29 06:07:30,146 []
2016-08-29 06:07:34,161 []
2016-08-29 06:07:38,176 []
2016-08-29 06:07:42,190 []
2016-08-29 06:07:46,105 []
2016-08-29 06:07:50,120 []
2016-08-29 06:07:54,135 []
2016-08-29 06:07:58,151 []
2016-08-29 06:08:02,166 []
2016-08-29 06:08:06,181 []
2016-08-29 06:08:10,196 []
2016-08-29 06:08:14,111 []
2016-08-29 06:08:18,126 []
2016-08-29 06:08:22,141 []
2016-08-29 06:08:26,156 []
2016-08-29 06:08:30,171 []
2016-08-29 06:10:32,145 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 06:10:32,154 Starting new HTTPS connection (1): slack.com
2016-08-29 06:10:32,584 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 06:10:32,587 []
2016-08-29 06:10:32,587 []
2016-08-29 06:10:32,688 []
2016-08-29 06:10:32,788 []
2016-08-29 06:10:33,391 []
2016-08-29 06:10:33,492 []
2016-08-29 06:10:36,101 []
2016-08-29 06:10:38,610 []
2016-08-29 06:10:39,113 []
2016-08-29 06:15:49,185 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472451039.000022', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 48, in process_message
    text = trans.decode_main(data['text'])
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/x_translate.py", line 329, in decode_main
    in_vocab, _ = data_utils.initialize_vocabulary(in_vocab_path)
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/data_utils_twitter.py", line 127, in initialize_vocabulary
    file = open(vocabulary_path,"w")
IOError: [Errno 2] No such file or directory: '/home/dev10635gce006/tensorflw/temp1/chat-master/datas/vocab_in.txt'
2016-08-29 06:15:50,964 []
2016-08-29 06:17:22,696 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 06:17:22,703 Starting new HTTPS connection (1): slack.com
2016-08-29 06:17:23,061 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 06:17:23,063 []
2016-08-29 06:17:23,064 []
2016-08-29 06:17:23,164 []
2016-08-29 06:17:23,265 []
2016-08-29 06:17:23,366 []
2016-08-29 06:17:26,879 []
2016-08-29 06:17:27,180 []
2016-08-29 06:17:27,482 []
2016-08-29 06:21:56,845 output from <module 'repeat' from '/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py'>
2016-08-29 06:21:56,952 []
2016-08-29 06:42:19,953 Initialized in: /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot
2016-08-29 06:42:20,076 Starting new HTTPS connection (1): slack.com
2016-08-29 06:42:20,438 /home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py
2016-08-29 06:42:20,440 []
2016-08-29 06:42:20,440 []
2016-08-29 06:42:20,541 []
2016-08-29 06:42:20,642 []
2016-08-29 06:42:20,943 []
2016-08-29 06:42:24,156 []
2016-08-29 06:42:28,173 []
2016-08-29 06:42:32,190 []
2016-08-29 06:42:36,106 []
2016-08-29 06:42:40,123 []
2016-08-29 06:42:44,140 []
2016-08-29 06:42:45,947 []
2016-08-29 06:42:48,155 []
2016-08-29 06:42:52,170 []
2016-08-29 06:42:56,184 []
2016-08-29 06:43:00,199 []
2016-08-29 06:43:04,112 []
2016-08-29 06:43:08,127 []
2016-08-29 06:43:12,141 []
2016-08-29 06:43:16,155 []
2016-08-29 06:43:20,169 []
2016-08-29 06:43:24,184 []
2016-08-29 06:43:28,198 []
2016-08-29 06:43:32,112 []
2016-08-29 06:43:36,126 []
2016-08-29 06:43:40,141 []
2016-08-29 06:43:44,155 []
2016-08-29 06:43:48,169 []
2016-08-29 06:43:52,184 []
2016-08-29 06:43:56,199 []
2016-08-29 06:44:00,112 []
2016-08-29 06:44:04,127 []
2016-08-29 06:44:08,142 []
2016-08-29 06:44:12,156 []
2016-08-29 06:44:16,171 []
2016-08-29 06:44:20,186 []
2016-08-29 06:44:24,200 []
2016-08-29 06:44:28,114 []
2016-08-29 06:44:32,129 []
2016-08-29 06:44:36,143 []
2016-08-29 06:44:40,158 []
2016-08-29 06:44:44,173 []
2016-08-29 06:44:45,879 []
2016-08-29 06:44:48,187 []
2016-08-29 06:44:48,288 []
2016-08-29 06:44:49,693 []
2016-08-29 06:44:51,299 []
2016-08-29 06:45:59,138 problem in module process_message {u'text': u'\u3053\u3093\u306b\u3061\u306f', u'ts': u'1472453091.000024', u'user': u'U1WT2UBLZ', u'team': u'T1WT2UBL1', u'type': u'message', u'channel': u'D25QGLCKG'}
Traceback (most recent call last):
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/rtmbot/core.py", line 166, in do
    eval("self.module." + function_name)(data)
  File "/home/dev10635gce006/tensorflow/temp1/bot/python-rtmbot/plugins/repeat/repeat.py", line 48, in process_message
    text = trans.decode_main(data['text'])
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/x_translate.py", line 346, in decode_main
    target_weights, bucket_id, True)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 225, in step
    outputs = session.run(output_feed, input_feed)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
FailedPreconditionError: Attempting to use uninitialized value embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/Linear/Bias
	 [[Node: embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/Linear/Bias/read = Identity[T=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/Linear/Bias"], _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/Linear/Bias)]]
Caused by op u'embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/AttnOutputProjection/Linear/Bias/read', defined at:
  File "./rtmbot.py", line 36, in <module>
    tf.app.run()
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "./rtmbot.py", line 15, in main
    trans.init_main()
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/x_translate.py", line 368, in init_main
    dec_model = create_model(sess, True)
  File "/home/dev10635gce006/tensorflow/temp1/chat-master/x_translate.py", line 107, in create_model
    forward_only=forward_only)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 138, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 1023, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 137, in <lambda>
    self.target_weights, buckets, lambda x, y: seq2seq_f(x, y, True),
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 114, in seq2seq_f
    feed_previous=do_decode)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 761, in embedding_attention_seq2seq
    initial_state_attention=initial_state_attention)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 686, in embedding_attention_decoder
    initial_state_attention=initial_state_attention)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 610, in attention_decoder
    output = linear([cell_output] + attns, output_size, True)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell.py", line 908, in _linear
    bias_start, dtype=dtype))
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 830, in get_variable
    custom_getter=custom_getter)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 673, in get_variable
    custom_getter=custom_getter)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 217, in get_variable
    validate_shape=validate_shape)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 202, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 536, in _get_single_variable
    validate_shape=validate_shape)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 211, in __init__
    dtype=dtype)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 323, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1098, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/dev10635gce006/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()

2016-08-29 06:46:01,192 []
2016-08-29 06:46:05,110 []
2016-08-29 06:46:09,128 []
2016-08-29 06:46:13,145 []
2016-08-29 06:46:17,162 []
2016-08-29 06:46:21,179 []
2016-08-29 06:46:25,196 []
2016-08-29 06:46:29,113 []
2016-08-29 06:46:31,021 []
2016-08-29 06:46:31,423 []
